import Head from 'next/head'
import MobileNav from '@components/MobileNav';
import { Inter } from '@next/font/google';
import cn from "classnames";
import { useState } from "react";
import styles from '../components/index.module.css'
import { motion, useTime, useTransform, useMotionValue, useCycle } from "framer-motion";
import { FadeIn } from '@components/FadeIn';
import { Gradient } from '@components/Gradient';
import Image from 'next/image';
import gradients from "../components/gradients.module.css";

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  // const [rotateSpeed, setRotateSpeed] = useState(8000)
  const time = useTime();
  const rotate = useTransform(time, [0, 15000], [0, 360], { clamp: false });
  const [hovering, setHovering] = useState(false);

  return (
    <>
      <Head>
        <title>Next Background Animation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-black text-white min-h-screen relative overflow-hidden">
        <div className={inter.className}>

          <MobileNav />

          <section id="home" className="w-full h-screen flex items-center justify-center mb-16">
            <div className="home_spotlight"></div>
            <div className="z-10 text-white">
              RINGS
            </div>
          </section>

          {/* https://loading.io/background/ */}
          <section id="ripple" className="relative min-h-screen h-screen flex items-center justify-center">
            <h1 className="font-extrabold text-center mb-10 sm:mb-20 text-4xl md:text-5xl p-4 bg-clip-text text-transparent bg-gradient-to-b from-white to-[#AAAAAA]">
              Ripple
            </h1>
          </section>

          {/* https://loading.io/background/ */}
          <section id="particles" className="relative min-h-screen h-screen flex items-center justify-center">
            <h1 className="font-extrabold text-center mb-10 sm:mb-20 text-4xl md:text-5xl p-4 bg-clip-text text-transparent bg-gradient-to-b from-white to-[#AAAAAA]">
              Particles
            </h1>
          </section>

          {/* https://loading.io/background/ */}
          <section id="disk" className="relative min-h-screen h-screen flex items-center justify-center">
            <h1 className="font-extrabold text-center mb-10 sm:mb-20 text-4xl md:text-5xl p-4 bg-clip-text text-transparent bg-gradient-to-b from-white to-[#AAAAAA]">
              Disk
            </h1>
          </section>

          {/* https://loading.io/background/ */}
          <section id="spotlight" className="relative min-h-screen h-screen flex items-center justify-center">
            <h1 className="font-extrabold text-center mb-10 sm:mb-20 text-4xl md:text-5xl p-4 bg-clip-text text-transparent bg-gradient-to-b from-white to-[#AAAAAA]">
              Spotlight
            </h1>
          </section>

          {/* https://loading.io/background/ */}
          <section id="interstellar" className="relative min-h-screen h-screen flex items-center justify-center">
            <h1 className="font-extrabold text-center mb-10 sm:mb-20 text-4xl md:text-5xl p-4 bg-clip-text text-transparent bg-gradient-to-b from-white to-[#AAAAAA]">
              Interstellar
            </h1>
          </section>

          {/* https://loading.io/background/ */}
          <section id="speedline" className="relative min-h-screen h-screen flex items-center justify-center">
            <h1 className="font-extrabold text-center mb-10 sm:mb-20 text-4xl md:text-5xl p-4 bg-clip-text text-transparent bg-gradient-to-b from-white to-[#AAAAAA]">
              Speedline
            </h1>
          </section>

          {/* https://loading.io/background/ */}
          <section id="bars" className="relative min-h-screen h-screen flex items-center justify-center">
            <h1 className="font-extrabold text-center mb-10 sm:mb-20 text-4xl md:text-5xl p-4 bg-clip-text text-transparent bg-gradient-to-b from-white to-[#AAAAAA]">
              Bars
            </h1>
          </section>

          {/* https://loading.io/background/ */}
          <section id="lotus" className="relative min-h-screen h-screen flex items-center justify-center">
            <h1 className="font-extrabold text-center mb-10 sm:mb-20 text-4xl md:text-5xl p-4 bg-clip-text text-transparent bg-gradient-to-b from-white to-[#AAAAAA]">
              Lotus
            </h1>
          </section>

          {/* https://loading.io/background/ */}
          <section id="field" className="relative min-h-screen h-screen flex items-center justify-center">
            <h1 className="font-extrabold text-center mb-10 sm:mb-20 text-4xl md:text-5xl p-4 bg-clip-text text-transparent bg-gradient-to-b from-white to-[#AAAAAA]">
              Field
            </h1>
          </section>

          <section className="min-h-screen flex items-center justify-center w-full">

            <div className="Header_marquee w-full">
              <div className="Header_marquee_content">
                <div className="w-full text-white flex flex-col gap-8 px-8 py-2">
                  <div className="h-28 w-full border border-neutral-600 flex items-center justify-center">1</div>
                  <div className="h-28 w-full border border-neutral-600 flex items-center justify-center">2</div>
                  <div className="h-28 w-full border border-neutral-600 flex items-center justify-center">3</div>
                  <div className="h-28 w-full border border-neutral-600 flex items-center justify-center">4</div>
                  <div className="h-28 w-full border border-neutral-600 flex items-center justify-center">5</div>
                  <div className="h-28 w-full border border-neutral-600 flex items-center justify-center">6</div>
                  <div className="h-28 w-full border border-neutral-600 flex items-center justify-center">7</div>
                  <div className="h-28 w-full border border-neutral-600 flex items-center justify-center">8</div>
                  <div className="h-28 w-full border border-neutral-600 flex items-center justify-center">9</div>
                  <div className="h-28 w-full border border-neutral-600 flex items-center justify-center">10</div>
                </div>
              </div>
            </div>
          </section>

          <section className="relative min-h-screen w-full flex items-center justify-center overflow-hidden">
            <FadeIn>
              <span
                className={cn(
                  "w-full absolute h-[1px] top-0 left-0 opacity-25",
                  gradients.gradientSectionBorderDivider
                )}
              />
              <span
                className={cn(
                  gradients.gradientSectionBorder,
                  gradients.gradientSectionBorderLeft,
                  "opacity-[0.15]"
                )}
              />
              <span
                className={cn(
                  gradients.gradientSectionBorder,
                  gradients.gradientSectionBorderRight,
                  "opacity-[0.15]"
                )}
              />
            </FadeIn>
            Border Glow
            <Gradient
              width={1200}
              height={300}
              className="bottom-[-200px] opacity-20"
              conic
            />
          </section>

          <section id="pattern" className="relative w-full h-screen flex items-center justify-center ">
            <span className="absolute top-0 left-0 right-0 w-full h-24 bg-gradient-to-b from-black to-transparent" />
            <span className="absolute bottom-0 z-10 left-0 right-0 w-full h-24 bg-gradient-to-t from-black to-transparent" />
            <div className="z-20 text-white">
              PATTERN
            </div>
          </section>

          <section id="patterns" className="relative w-full h-full min-h-screen flex items-center justify-center mb-24 sm:pt-16 md:pt-0">
            <FadeIn className="z-10 mt-8 sm:mt-40 md:mt-0 md:flex justify-center md:gap-16 space-y-8 sm:space-y-12 md:space-y-0 w-full">
              <div className="w-full h-[180px] md:w-1/6 relative flex items-center justify-center">
                <div className="absolute z-10 min-w-[550px] min-h-[550px] md:min-w-[600px] md:min-h-[600px]">
                  <Image
                    alt="Turborepo"
                    src="/pack-hexagons.svg"
                    fill="true"
                  // className="block"
                  />
                </div>
                <div className="absolute z-10 flex items-center justify-center w-64 h-64">
                  <Gradient
                    small
                    width={120}
                    height={120}
                    conic
                    className="opacity-100"
                  />
                </div>
                <div className="w-[150px] h-[150px] z-10">
                  <Image
                    alt=""
                    src={`/pack-logo.svg`}
                    fill="true"
                  // className="block"
                  />
                </div>
              </div>
              <div className="w-full h-[180px] md:w-1/6 flex items-center justify-center">
                <h1 className="text-6xl sm:text-8xl text-transparent font-bold bg-clip-text bg-gradient-to-r from-yellow-500 to-sky-600">
                  {/* <span className={eb.className}>&</span> */}
                  &
                </h1>
              </div>
              <div className="w-full h-[180px] md:w-1/6 relative flex items-center justify-center">
                <div className="absolute min-w-[550px] min-h-[550px] md:min-w-[600px] md:min-h-[600px]">
                  <Image
                    alt="Turborepo"
                    src="/pack-hexagons.svg"
                    fill="true"
                    className="block"
                  />
                </div>
                <div className="absolute z-10 flex items-center justify-center w-64 h-64">
                  <Gradient
                    small
                    width={120}
                    height={120}
                    conic
                    className="opacity-100"
                  />
                </div>
                <div className="w-[150px] h-[150px] z-10">
                  <Image
                    alt=""
                    src={`/pack-logo.svg`}
                    fill="true"
                    className="block"
                  />
                </div>
              </div>
            </FadeIn>
            <Gradient
              width={1000}
              height={500}
              className="top-[-20px] opacity-20 "
              conic
            />
            <div className="absolute top-0 z-10 w-full h-24 from-black to-transparent bg-gradient-to-b" />
          </section>

          <section className="relative w-full h-screen flex items-center justify-center pb-16">
            <span className="absolute bottom-0 z-[5] w-full h-48 bg-gradient-to-t from-black to-transparent" />
            <Gradient
              width={1000}
              height={500}
              className="top-32 opacity-20"
              conic
            />
            <div className="absolute top-0 z-[5] w-full h-48 from-black to-transparent bg-gradient-to-b" />
            <div className="z-10 text-white">
              RINGS
            </div>
          </section>

          <section className="relative min-h-screen">
            <FadeIn
              noVertical
              className="font-sans pt-48 w-auto flex justify-between gap-8 items-center flex-col relative z-0"
            >
              <FadeIn className="z-10 flex items-center justify-center w-full ">
                <div className="absolute min-w-[500px] min-h-[500px]">
                  <Image
                    alt="Turborepo"
                    src="/hero-circles.svg"
                    width={500}
                    height={500}
                    className="block"
                  />
                </div>
                <div className="absolute z-10 flex items-center justify-center w-64 h-64">
                  <Gradient
                    small
                    width={120}
                    height={120}
                    conic
                    className="dark:opacity-100 opacity-40"
                  />
                </div>
                <div className="w-[120px] h-[120px] z-10">
                  <Image
                    alt=""
                    src={`/hero-logo.svg`}
                    width={120}
                    height={120}
                    className="block"
                  />
                </div>
              </FadeIn>
              <Gradient
                width={1000}
                height={1000}
                className="top-[-500px] dark:opacity-20 opacity-[0.15]"
                conic
              />
              <div className="absolute top-0 z-10 w-full h-48 from-black to-transparent bg-gradient-to-b" />
            </FadeIn>
          </section>

          <section className="relative min-h-screen flex items-center justify-center">
            <FadeIn
              noVertical
              className="w-auto flex justify-between gap-8 items-center flex-col relative z-0"
            >
              <FadeIn className="z-10 sm:flex items-center justify-center flex-wrap gap-64 space-y-64 sm:space-y-0 w-full ">
                <div className="relative flex items-center justify-center">
                  <div className="absolute min-w-[500px] min-h-[500px]">
                    <Image
                      alt="Turborepo"
                      src="/hero-circles.svg"
                      width={500}
                      height={500}
                      className="block"
                    />
                  </div>
                  <div className="absolute z-10 flex items-center justify-center w-64 h-64">
                    <Gradient
                      small
                      width={120}
                      height={120}
                      conic
                      className="dark:opacity-100 opacity-40"
                    />
                  </div>
                  <div className="w-[120px] h-[120px] z-10">
                    <Image
                      alt=""
                      src={`/hero-logo.svg`}
                      width={120}
                      height={120}
                      className="block"
                    />
                  </div>
                </div>
                <div className="relative flex items-center justify-center">
                  <div className="absolute min-w-[500px] min-h-[500px]">
                    <Image
                      alt="Turborepo"
                      src="/hero-circles.svg"
                      width={500}
                      height={500}
                      className="block"
                    />
                  </div>
                  <div className="absolute z-10 flex items-center justify-center w-64 h-64">
                    <Gradient
                      small
                      width={120}
                      height={120}
                      conic
                      className="dark:opacity-100 opacity-40"
                    />
                  </div>
                  <div className="w-[120px] h-[120px] z-10">
                    <Image
                      alt=""
                      src={`/hero-logo.svg`}
                      width={120}
                      height={120}
                      className="block"
                    />
                  </div>
                </div>
              </FadeIn></FadeIn>
          </section>

          <section className="relative min-h-screen">
            <FadeIn
              noVertical
              className="font-sans pt-48 w-auto flex justify-between gap-8 items-center flex-col relative z-0"
            >
              <FadeIn className="z-10 flex items-center justify-center w-full ">
                <div className="absolute min-w-[500px] min-h-[500px]">
                  <Image
                    alt="Turborepo"
                    src="/pack-hexagons.svg"
                    width={500}
                    height={500}
                    className="block"
                  />
                </div>
                <div className="absolute z-10 flex items-center justify-center w-64 h-64">
                  <Gradient
                    small
                    width={120}
                    height={120}
                    conic
                    className="dark:opacity-100 opacity-40"
                  />
                </div>
                <div className="w-[120px] h-[120px] z-10">
                  <Image
                    alt=""
                    src={`/pack-logo.svg`}
                    width={120}
                    height={120}
                    className="block"
                  />
                </div>
              </FadeIn>
              {/* <Gradient
                width={1000}
                height={1000}
                className="top-[-500px] dark:opacity-20 opacity-[0.15]"
                conic
              /> */}
              <div className="absolute top-0 z-10 w-full h-48 from-black to-transparent bg-gradient-to-b" />
            </FadeIn>
          </section>

          <section className="relative">
            <div className="flex flex-wrap w-full items-center justify-center gap-6">
              <FadeIn delay={0.3}>
                <div
                  className={cn(
                    styles["counter-border"],
                    "no-underline"
                  )}
                  onMouseEnter={() => setHovering(true)}
                  onMouseLeave={() => setHovering(false)}
                >
                  <motion.i
                    initial="visible"
                    animate={{ opacity: 1 }}
                    variants={{
                      hidden: { opacity: 0 },
                      active: { opacity: 1 },
                    }}
                    aria-hidden="true"
                  ></motion.i>
                  <div className="p-8 rounded-lg">
                    <div className="relative flex items-center justify-center">
                      <div className="z-10 absolute w-54 h-54 inset-0 bg-gradient-to-b from-sky-700 to-green-500 mix-blend-normal opacity-[0.15] blur-[60px]" />
                      <div className="bg-black h-64 w-64">
                      </div>
                    </div>
                    <div className="flex justify-center">
                      <span className="text-2xl no-underline mt-2 font-bold text-gray-200 tracking-wide">Title</span>
                    </div>
                  </div>
                </div>
              </FadeIn>
              <FadeIn delay={0.5}>
                <div
                  className={cn(
                    styles["counter-border-blue"],
                    "no-underline"
                  )}
                  onMouseEnter={() => setHovering(true)}
                  onMouseLeave={() => setHovering(false)}
                >
                  <motion.i
                    initial="visible"
                    animate={{ opacity: 1 }}
                    variants={{
                      hidden: { opacity: 0 },
                      active: { opacity: 1 },
                    }}
                    aria-hidden="true"
                  ></motion.i>
                  <div className="p-8 rounded-lg">
                    <div className="relative flex items-center justify-center">
                      <div className="z-10 absolute w-54 h-54 inset-0 bg-gradient-to-b from-red-800 to-yellow-500 mix-blend-normal opacity-[0.15] blur-[60px]" />
                      <div className="bg-black h-64 w-64">
                      </div>
                    </div>
                    <div className="flex justify-center">
                      <span className="text-2xl no-underline mt-2 font-bold text-gray-200 tracking-wide">Title</span>
                    </div>
                  </div>
                </div>
              </FadeIn>
            </div>
          </section>

          <section id="title" className="relative h-screen flex items-center">
            <FadeIn delay={0.5}>
              <h1 className="z-10 mx-6 font-extrabold text-5xl lg:text-6xl leading-tight text-center mb-4 bg-clip-text text-transparent bg-gradient-to-b from-white to-[#AAAAAA]">
                Gradient Title
              </h1>
            </FadeIn>
            <span className="absolute bottom-0 left-0 right-0 w-full h-48 bg-gradient-to-t from-black to-transparent" />
          </section>

          <section className="relative w-full h-screen flex items-center justify-center">
            <motion.div
              className="absolute inset-0"
              style={{
                rotate,
                backgroundSize: 'cover',
                backgroundRepeat: 'no-repeat',
                backgroundPosition: '50%',
                backgroundImage: 'url(/ring-small.svg)'
              }}
            />
            <div className="home_spotlight"></div>
            <div className="z-10 text-white">
              RINGS
            </div>
          </section>

          <section id="grid" className="w-full h-screen flex items-center justify-center">
            <div className="grid-radial"></div>
            <motion.div
              className="resources_blob absolute inset-0 left-0"
            />
            <div className="resources_blob"></div>
            <div className="z-10 text-white text-center">
              GRID
            </div>
          </section>

          <section id="galeri" className="w-full h-screen pb-16">
            <div
              className="absolute top-0 left-0 right-0 bottom-0 bg-transparent"
              style={{
                backgroundSize: 'cover',
                backgroundRepeat: 'no-repeat',
                backgroundPosition: '50%',
                backgroundImage: 'url(/glow.svg)'
              }}
            />
            <div className="relative z-10 h-screen flex items-center justify-center">
              GALERI
            </div>
          </section>

          <section id="union" className="w-full h-screen">
            <div className="h-screen flex items-center justify-center">
              UNION
            </div>
          </section>

          <section id="gridd" className="h-screen relative">
            <div className="gridd-bg"></div>
            <div className="relative z-10 flex items-center justify-center h-screen">
              GRIDD
            </div>
          </section>

          <section id="gridd" className="relative h-screen">
            <span className="absolute z-10 top-0 right-0 left-0 w-full h-64 bg-gradient-to-b from-black to-transparent" />
            <span className="absolute z-10 bottom-0 right-0 left-0 w-full h-64 bg-gradient-to-t from-black to-transparent" />
            <span className="absolute z-10 top-0 bottom-0 left-0 w-64 h-full bg-gradient-to-r from-black to-transparent" />
            <span className="absolute z-10 top-0 bottom-0 right-0 w-64 h-full bg-gradient-to-l from-black to-transparent" />
            <motion.div
              id="gridd-bg"
              animate={{
                scale: [1, 1.1, 1, 0.9],
                rotate: [0, 90, 180, 270, 360],
              }}
              transition={{
                duration: 2,
                ease: "easeInOut",
                times: [0.9, 1, 0.9, 1],
                repeat: Infinity,
              }}
            />
            <div className="relative z-20 flex items-center justify-center h-screen">
              GRIDD
            </div>
          </section>

          <section id="gridd" className="relative h-screen">
            <span className="absolute z-10 top-0 bottom-0 left-0 w-64 h-full bg-gradient-to-r from-black to-transparent" />
            <span className="absolute z-10 top-0 bottom-0 right-0 w-64 h-full bg-gradient-to-l from-black to-transparent" />
            <div className="zoom-in-out-box"></div>
            <div className="relative z-20 flex items-center justify-center h-screen">
              GRIDD
            </div>
          </section>

          <section className="relative z-[1] h-screen w-screen ">
            <span className={cn(styles.leftLights, "opacity-100")} />
            <span className={cn(styles.rightLights, "opacity-100")} />
            <span className="absolute bottom-0 left-0 right-0 w-full h-48 bg-gradient-to-t from-black to-transparent" />
            <span className="bg-black absolute top-[10vh] left-0 right-0 w-full h-[30vh]" />
            <span className="bg-gradient-to-b from-black to-transparent absolute top-[20vh] left-0 right-0 w-full h-[550vh]"></span>
            <div className="container ![perspective:1000px]">
              <div className="absolute inset-0"
                style={{
                  transform: "rotateX(75deg)",
                }}
              >
                <div className="lines" />
              </div>
            </div>
            <div className="relative flex items-center h-screen justify-center">
              aa
            </div>
          </section>

        </div>
      </main >
    </>
  )
}
